Track computational requirements
meyer-lab/scCP pull request #482
Opened 2024-12-18 18:52 UTC by armaan-abraham

2024-12-19 03:11 UTC, aarmey requested changes
A few comments. Please also look at why the testing is failing, and merge changes with main.

2024-12-19 03:11 UTC, aarmey commented on imports.ipynb
> +  {
Should these be removed?

2024-12-19 03:11 UTC, aarmey commented on sccp/figures/figureS7.py
> +    print("yo")
Please take care of basic editing here.

2024-12-19 03:11 UTC, aarmey commented on sccp/imports.py
> +    print(metafile.columns)
Remove.

2025-01-06 20:52 UTC, aarmey approved these changes
This all looks good.

2025-01-06 20:53 UTC, andrewram4287 commented
> @aarmey Sorry, I definitely should have checked the PR over before tagging you! I have cleaned things up, and made some updates centered around increasing the number of genes used in the benchmark. The build is failing, but this is caused by issues that existed before this PR and are unrelated. If you'd like, I can create another PR to go through these issues, but I think a separate PR to do so is best.

@armaan-abraham Thanks for seeing that issue. I will fix that issue on another PR!

2025-01-06 20:53 UTC, aarmey commented
@armaan-abraham @andrewram4287 I think the build and test failures here are also on main. We should fix these, but that is unrelated to this PR.

2025-01-06 21:32 UTC, merged